###register request

post http://localhost:3000/auth/register
Content-Type: application/json

{
  "username" : "ali.jafar",
  "email" : "ali_jafari@yaho.com",
  "mobile" : "09163422689",
  "password" : "abv123",
  "confirm_password" : "abv123"
}