### Create Team
post http://localhost:3000/team/craete
Content-Type: application/json
Authorization: Bearer {{$dotenv token}}

{
  "name" : "team-mohammad",
  "description" : "team-mohammad"
}

### Get List Of Teams
Get http://localhost:3000/team/getListOfTeams
Content-Type: application/json
Authorization: Bearer {{$dotenv token}}

### Get Team By Id
Get http://localhost:3000/team/63234507bde557a0b152dc71
Content-Type: application/json
Authorization: Bearer {{$dotenv token}}

### Get MyTeam
Get http://localhost:3000/team
Content-Type: application/json
Authorization: Bearer {{$dotenv token}}

### Delete Team By Id
Delete http://localhost:3000/team/remove/6320e7d42d35e31e291204b9
Content-Type: application/json
Authorization: Bearer {{$dotenv token}}

### Invite User To Team 
Get http://localhost:3000/team/invite/63234c7f3569bdf852328f2c/reza
Content-Type: application/json
Authorization: Bearer {{$dotenv token}}

### update Team 
Put http://localhost:3000/team/update/6323740fb3274d1c4327d42a
Content-Type: application/json
Authorization: Bearer {{$dotenv token}}

{
  "name" : "Edited Team By Reza",
  "Description" : "Edited Team By Reza"
}