### Create Team
post http://localhost:3000/team/craete
Content-Type: application/json
Authorization: Bearer {{$dotenv token}}

{
  "name" : "SamEx",
  "description" : "SamEx Market"
}

### Get List Of Teams
Get http://localhost:3000/team/getListOfTeams
Content-Type: application/json
Authorization: Bearer {{$dotenv token}}

### Get Team By Id
Get http://localhost:3000/team/6320b2b31379ceaf597b25fa
Content-Type: application/json
Authorization: Bearer {{$dotenv token}}

### Get MyTeam
Get http://localhost:3000/team
Content-Type: application/json
Authorization: Bearer {{$dotenv token}}

### Delete Team By Id
Delete http://localhost:3000/team/remove/6320e7d42d35e31e291204b9
Content-Type: application/json
Authorization: Bearer {{$dotenv token}}
